### PR TITLE
Refactor

### LINKED ISSUE #53: Decide how to best allow user to specify auxiliary fields
Note that a BGC model needs to have a `biogeochemical_auxiliary_fields` method that returns a NamedTuple of the form `(field_name = Oceananigans Field object,...)`. 

Currently, in Agate the user can add auxiliary field names (e.g., PAR) when creating a model but they don't actually pass the field specification anywhere. Instead, we create the PAR field within the `run_box_model` function and the `biogeochemical_auxiliary_fields` method is defined within the `OceanBioME.Biogeochemistry` object instantiated within that function. 

This is clearly suboptimal. Either, the user should actually define auxiliary fields in the model specification or we should not let them append aux field variable names to the model and instead handle everything inside a wrapper like `run_box_model`.

### PR DESCRIPTION
**Pull request by radka-j**
Closes #53 

## PR overview

This PR adds a `define_bgc_tracers` method which is now the main Agate interface for dynamically defining tracer functions. We also remove some existing wrapper functions and instead expect users to compose their Agate models with OceanBioME and/or Oceananigans objects themselves.  

The workflow for the user is as follows:

```Julia
using Agate
using OceanBioME
using OceanBioME: Biogeochemistry
using Oceananigans
```

1. Define ecology type (**Agate**)

```Julia
NPZD = define_bgc_tracers(parameters, tracers) 
```

2. Specify geometry/grid (**OceanBioME** for Box, otherwise **Oceananigans**)

<table style="table-layout: fixed ; width: 100%;">
<tr>
<th>Box Model</th>
<th>Column</th>
</tr>
<tr>
<td width>
  
```Julia 
grid = BoxModelGrid()             
```

</td>
<td>

```Julia
grid = RectilinearGrid(; 
    size=(1, 1, 40), 
    extent=(20meters, 20meters, 200meters)
)
```

</td>
</tr>
</table>

3. Define full Biogeochemistry with auxiliary fields defined on grid (**OceanBioME**)

```Julia
biogeochemistry = Biogeochemistry(
    NPZD(); 
    light_attenuation=FunctionPAR(; grid)
)
```

4. Use box model (**OceanBioME**) or specify ocean physics (**Oceananigans**)

<table style="table-layout: fixed ; width: 100%;">
<tr>
<th>Box Model</th>
<th>Column</th>
</tr>
<tr>
<td>
  
```Julia
full_model =  BoxModel(;          
    biogeochemistry         
)
```

</td>
<td >

```Julia
κₜ = ....
full_model = NonhydrostaticModel(; 
    grid, 
    closure=ScalarDiffusivity(; ν=κₜ, κ=κₜ), 
    biogeochemistry 
)
```

</td>
</tr>
</table>

5. Simulate (**Oceananigans**)

```Julia
Simulation(full_model, Δt....)
```

### CODE REVIEW

**Comment by nanophyto** [comment]
> * Instead of asking the user to specify the struct name, I generate a random string of length 12 and use that as the name to avoid the user having to specify this twice, they can now do:
>   
>   * `model_name = define_bgc_tracers(parameters, tracers)`
> * Are there any potential issues with the above?

In what context might the user need to know/access the `model_name`? Would it make sense to combine three random words to make things more legible instead? e.g. "bluecarhouse"

Should we also allow users to define their own `model_name` (but default to random string)?

And  maybe we can rename `model_name` to `model_identifier` so it is not confused with `bg_tracer` object names (e.g. `NPZD`).

**Comment by nanophyto** [comment]
> If the user is running a more complex ocean model they have to do an extra step:
> 
> 1. define the tracers type with e.g., `NPZD = define_bgc_tracers(...)`
> 2. `bgc_tracers=NPZD()`
> 3. use `model = create_bgc_model(bgc_tracers,....)` to specify light attenuation and sinking velocities.
> 4. Pass the model object into an Oceanigans model (this can be 1D/2D/3D) where boundary conditions are also specified.

Another option here is to pass the Oceananigans.jl object into Agate.jl instead.

**Comment by radka-j** [comment]
> In what context might the user need to know/access the `model_name`? Would it make sense to combine three random words to make things more legible instead? e.g. "bluecarhouse"
> 
> Should we also allow users to define their own `model_name` (but default to random string)?
> 
> And maybe we can rename `model_name` to `model_identifier` so it is not confused with `bg_tracer` object names (e.g. `NPZD`).

The motivation for this change was to avoid having the user define the model name twice, i.e.: `NPZD = define_tracers(:NPZD,...)`.

So as before, we are reassign the model identifier (e.g., `Agate.Models.Dynamic.NPZD`) to a user defined shorter one but instead it's more like `NPZD = Agate.Models.Dynamic.qwertyuiopas`. The user still then just uses `NPZD()` to instantiate the object (i.e., they never have to care about what it's called under the hood).

The concern I have is purely about uniqueness. If the user defines several different models within the same session we have to make sure there is never a case where one tracer definition is overwritten with a new one. I like the idea that the user could choose to not create a random identifier.

**Comment by radka-j** [comment]
@nanophyto this is now ready for review again

**Pull request merged**
